### ISSUE TITLE
Errors on start up

### ISSUE THREAD

**Issue by Chris230291** [fHDHR/fHDHR_plugin_origin_locast#21]
Trying to use locast but gives the following errors...
```
[2021-02-27 20:24:26,415] INFO - Found Origin: locast
[2021-02-27 20:24:26,415] INFO - Logging into Locast using username ************...
Checking and Installing Core Dependencies.
missing. Attempting installation
Installation failed
Traceback (most recent call last):
File "/app/main.py", line 16, in <module>
sys.exit(run.main(SCRIPT_DIR, fHDHR_web, deps))
File "/app/fHDHR/cli/run.py", line 129, in main
returned_code = start(args, script_dir, fHDHR_web, deps)
File "/app/fHDHR/cli/run.py", line 109, in start
return run(settings, logger, db, script_dir, fHDHR_web, plugins, versions, web, scheduler, deps)
File "/app/fHDHR/cli/run.py", line 32, in run
fhdhr = fHDHR_OBJ(settings, logger, db, plugins, versions, web, scheduler, deps)
File "/app/fHDHR/__init__.py", line 42, in __init__
self.fhdhr.origins = Origins(self.fhdhr)
File "/app/fHDHR/origins/__init__.py", line 25, in __init__
self.origin_selfadd()
File "/app/fHDHR/origins/__init__.py", line 43, in origin_selfadd
self.origins_dict[method] = self.fhdhr.plugins.plugins[plugin_name].Plugin_OBJ(plugin_utils)
File "/app/plugins/fHDHR_plugin_origin_locast/origin/__init__.py", line 25, in __init__
self.login()
File "/app/plugins/fHDHR_plugin_origin_locast/origin/__init__.py", line 142, in login
self.token = self.get_token()
File "/app/plugins/fHDHR_plugin_origin_locast/origin/__init__.py", line 172, in get_token
loginRes = loginReq.json()
File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json
return complexjson.loads(self.text, **kwargs)
File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
return _default_decoder.decode(s)
File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
obj, end = self.raw_decode(s)
File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by deathbybandaid** [comment]
Did you donate?

**Comment by Chris230291** [comment]
I haven't. I am not in the US. I just wanted to see if it would work.

**Comment by deathbybandaid** [comment]
This should fix the error you're seeing. Locast requires a donation to watch, and also only works in the US*.

https://github.com/fHDHR/fHDHR_plugin_origin_locast/pull/22

**Comment by Chris230291** [comment]
Do the settings not fool it into working without a VPN?

**Comment by deathbybandaid** [comment]
Spoofing your location violates the Terms of Service for Locast, and I cannot condone doing so.

Those settings are used for when Locast detects a user in the wrong DMA.
